import type { Metadata } from 'next';
import '../globals.css';
import { Header } from './components';

export const metadata: Metadata = {
  title: 'Мой блог',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <div>
      <Header />
      <body>{children}</body>
    </div>
  );
}
